[package]
name = "rust_simple_chat_client"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }
eframe = "0.28.1"
egui = "0.28.1"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
